### ISSUE TITLE
50% Kg

### ISSUE THREAD

**Issue by ruomusu** [mlvlab/NuTrea#2]
Hello, may I ask if there is an incomplete kg dataset in the paper

**Comment by imhgchoi** [comment]
Hello, we have used the incomplete KG dataset provided by GraftNet.
The datasets can be found [here](http://curtis.ml.cmu.edu/datasets/graftnet/).
Thank you.

**Comment by ruomusu** [comment]
Thank you very much, it has been very helpful to me. I have another question. Can I replace this dataset with my own dataset

**Comment by imhgchoi** [comment]
Yes, as long as the data format matches that of the experiment data, I think it should work.
