### ISSUE TITLE
Question about instruction-update

### ISSUE THREAD

**Issue by nanxfu** [mlvlab/NuTrea#3]
Thank you for your greate work!
I am confusion with the process of instruction-update in your supplement material.
![1714054480249](https://github.com/mlvlab/NuTrea/assets/36119106/5b681a97-13fe-4004-985a-dd3d1a4afaf6)

Please give me a brief introduction to the process of instruction-update or the code segment in the repository

**Comment by imhgchoi** [comment]
Apoligies for getting back to you so late.

You may want to check the code starting from [here](https://github.com/mlvlab/NuTrea/blob/52becceef5e48ae8f9b3f10347a469b4780a1884/src/models/NuTrea/nutrea.py#L331).

Thank you.
